### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by peva3** [dhbikoff/plex-sync#1]
Interested in this, any more info on what this is/does?

**Comment by dhbikoff** [comment]
It's a web app that publishes a local Plex server for external access. 

Plex allows you to view your media from anywhere if the server is published. My local Plex server disconnects often and doesn't automatically republish for external access. The app sends a command to the local server to reconnect.

The plexPublish.sh script can be run as a cron job to reconnect automatically if the connection drops, making the web app unnecessary for my use really.
